### ISSUE TITLE
yii2 v2.0.14

### ISSUE THREAD

**Issue by lesha724** [edgardmessias/yii2-firebird#11]
Declaration of edgardmessias\db\firebird\QueryBuilder::batchInsert() should be compatible with yii\db\QueryBuilder::batchInsert($table, $columns, $rows, &$params = Array)

**Comment by dicrtarasov** [comment]
This is under php 7.0

**Comment by edgardmessias** [comment]
I'll work on this as soon as possible.

**Comment by lesha724** [comment]
@edgardmessias Do you need some help?

**Comment by dicrtarasov** [comment]
There are just 2 lines changes in QueryBuilder (add $params argument to functions declarations) and all works perfect :)I makes fix in my local copy and verify that all is fine :)2:07, 27 февраля 2018 г., Alexey <notifications@github.com>:@edgardmessias Do you need help?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by edgardmessias** [comment]
We need update tests

**Comment by edgardmessias** [comment]
dev-master is OK.

Now need rebuild unit tests for 2.0.14

**Comment by marcinmisiak** [comment]
similar bug:
prepareInsertSelectSubQuery($columns, $schema)
should be:
 prepareInsertSelectSubQuery($columns, $schema, $params =[])

**Comment by edgardmessias** [comment]
I will work to make compatible with 2.0.15

**Comment by edgardmessias** [comment]
Unit tests is ok for 2.0.15, now, wait the release

**Comment by edgardmessias** [comment]
New release: https://github.com/edgardmessias/yii2-firebird/releases/tag/0.10.0
